### ISSUE TITLE
Deprecate and remove APIs

### ISSUE THREAD

**Issue by methane** [pallets/flask#1182]
When making Flask 1.0, could you remove some old APIs?

- [x] deprecate `flask.ext`, see #1484 and #1135 
- [x] remove modules, see #1204 and #861
- [x] deprecate `*_session()`
- [x] Allow all objects in JSON, see #673, #1177, #248, #170, #510
- [x] deprecate `request.json,` see #1206 and #1204 
- [x] remove support for name guessing from `send_file` #1427

**Comment by merqurio** [comment]
:+1:

**Comment by avilaton** [comment]
:+1:  for Allow all objects in JSON

**Comment by untitaker** [comment]
https://github.com/mitsuhiko/flask/pull/1291 just got merged, and after doing most of the API breakages, I'd like to make some sort of alpha for Flask 1.0.

**Comment by ThiefMaster** [comment]
Would it make sense to remove the deprecated `Flask.modules` property, too?

**Comment by untitaker** [comment]
Thought it was already removed! PRs welcome.

**Comment by ThiefMaster** [comment]
#1510

**Comment by flying-sheep** [comment]
where’s the alpha? [people start believeing flask is dead](https://www.reddit.com/r/Python/comments/3xi6o9/whats_the_future_of_flask/)

**Comment by jeffwidman** [comment]
"Allow all objects in json" should be checked, it was fixed in #1671

**Comment by jeffwidman** [comment]
> deprecate flask.ext

I marked this as fixed by #1484.

**Comment by SkiftCreative** [comment]
Working on this in the pycon sprint

**Comment by SkiftCreative** [comment]
In regards to the removal or deprecation of the `*_session` methods, can you elaborate on why those should be deprecated or removed? I searched the code base and they don't seem to be deprecated already. So It appears we need to do that first. I also looked around with @davidism at the pycon sprints and we could not figure out why they needed to be removed or deprecated, or why.

**Comment by davidism** [comment]
#1849 removed send_file name guessing

**Comment by davidism** [comment]
@untitaker did you add the "remove *_session" task?  What were you referring to?

**Comment by methane** [comment]
I meant make_null_session, open_session and save_session in Flask class.
session_interface is recommended way.

But I notice they aren't marked as deprecated for now.
So we can't remove them. How about start deprecating?
